- name: install git
  apt: name=git state=present

- name: Update APT package cache
  apt: update_cache=yes

- name: Upgrade APT to the lastest packages
  apt: upgrade=safe


- name: Install role-independent useful system packages
  apt: >
    pkg={{','.join(common_debian_pkgs)}} install_recommends=yes
    state=present update_cache=yes
