- name: install git
  apt: name=git state=present

- name: Update APT package cache
  apt: update_cache=yes

- name: Upgrade APT to the lastest packages
  apt: upgrade=safe

- file: name=/etc/locale.gen state=absent
  sudo: yes

- name: Setup ufw
  shell: ufw allow 22/tcp

- name: Setup ufw
  shell: ufw allow 80/tcp

- name: Setup ufw
  shell: ufw allow 443/tcp

- name: Enable ufw
  shell: echo 'y' | ufw enable

- locale_gen: name=fr_FR.UTF-8 state=present

- name: add authorized_keys
  authorized_key:  user=root
                    key="{{ lookup('file', 'public_keys/ssh_keys') }}"

- name: template /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts mode=0644

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh

- hostname: name={{ item.name }}
  with_items: hostname

- name: Install role-independent useful system packages
  # do this before log dir setup; rsyslog package guarantees syslog user present
  apt: >
    pkg={{','.join(common_debian_pkgs)}} install_recommends=yes
    state=present update_cache=yes

- name: Create common log directory
  file: >
    path={{ COMMON_LOG_DIR }} state=directory owner=syslog
    group=syslog mode=0755
