- name: install git
  apt: name=git state=present

- name: Update APT package cache
  apt: update_cache=yes

- name: Upgrade APT to the lastest packages
  apt: upgrade=safe



- name: add authorized_keys
  authorized_key:  user=root
                    key="{{ lookup('file', 'public_keys/ssh_keys') }}"




- hostname: name={{ item.name }}
  with_items: hostname

- name: Install role-independent useful system packages
  apt: >
    pkg={{','.join(common_debian_pkgs)}} install_recommends=yes
    state=present update_cache=yes
